name: jejom-llama
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2024.7.4=hf0a4a13_0
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.46.0=hfb93653_0
  - libzlib=1.3.1=hfb2fe0b_1
  - ncurses=6.5=hb89a1cb_0
  - openssl=3.3.1=hfb2fe0b_2
  - pip=24.2=pyhd8ed1ab_0
  - python=3.12.5=h30c5eda_0_cpython
  - readline=8.2=h92ec313_1
  - setuptools=72.1.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
      - aiohappyeyeballs==2.3.6
      - aiohttp==3.10.3
      - aiosignal==1.3.1
      - alembic==1.13.2
      - annotated-types==0.7.0
      - anyio==4.4.0
      - appdirs==1.4.4
      - asgiref==3.8.1
      - attrs==24.2.0
      - backoff==2.2.1
      - bcrypt==4.2.0
      - beautifulsoup4==4.12.3
      - boto3==1.34.162
      - botocore==1.34.162
      - build==1.2.1
      - cachetools==5.4.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - chroma-hnswlib==0.7.3
      - chromadb==0.4.24
      - click==8.1.7
      - cohere==5.8.1
      - coloredlogs==15.0.1
      - crewai==0.51.1
      - crewai-tools==0.8.3
      - dataclasses-json==0.6.7
      - decorator==5.1.1
      - deprecated==1.2.14
      - deprecation==2.1.0
      - dirtyjson==1.0.8
      - distro==1.9.0
      - docker==7.1.0
      - docstring-parser==0.16
      - docx2txt==0.8
      - embedchain==0.1.120
      - fastapi==0.112.1
      - fastavro==1.9.5
      - filelock==3.15.4
      - flatbuffers==24.3.25
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - google-api-core==2.19.1
      - google-auth==2.33.0
      - google-cloud-aiplatform==1.62.0
      - google-cloud-bigquery==3.25.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.12.5
      - google-cloud-storage==2.18.2
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.63.2
      - gptcache==0.1.44
      - greenlet==3.0.3
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.65.4
      - grpcio-status==1.62.3
      - grpcio-tools==1.62.3
      - h11==0.14.0
      - h2==4.1.0
      - hpack==4.0.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - httpx-sse==0.4.0
      - huggingface-hub==0.24.5
      - humanfriendly==10.0
      - hyperframe==6.0.1
      - idna==3.7
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.2
      - iniconfig==2.0.0
      - instructor==1.3.3
      - jinja2==3.1.4
      - jiter==0.4.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - json-repair==0.25.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - kubernetes==30.1.0
      - lancedb==0.5.7
      - langchain==0.2.14
      - langchain-cohere==0.1.9
      - langchain-community==0.2.12
      - langchain-core==0.2.32
      - langchain-experimental==0.0.64
      - langchain-huggingface==0.0.3
      - langchain-openai==0.1.21
      - langchain-text-splitters==0.2.2
      - langchain-upstage==0.1.7
      - langsmith==0.1.99
      - llama-index-core==0.10.66
      - llama-index-llms-openai==0.1.29
      - llama-index-llms-upstage==0.1.4
      - mako==1.3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - mdurl==0.1.2
      - mem0ai==0.0.9
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.8.1
      - nodeenv==1.9.1
      - numpy==1.26.4
      - oauthlib==3.2.2
      - onnxruntime==1.19.0
      - openai==1.40.8
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-instrumentation==0.47b0
      - opentelemetry-instrumentation-asgi==0.47b0
      - opentelemetry-instrumentation-fastapi==0.47b0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-util-http==0.47b0
      - orjson==3.10.7
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - parameterized==0.9.0
      - pillow==10.4.0
      - pluggy==1.5.0
      - portalocker==2.10.1
      - posthog==3.5.0
      - proto-plus==1.24.0
      - protobuf==4.25.4
      - pulsar-client==3.5.0
      - py==1.11.0
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - pylance==0.9.18
      - pypdf==4.3.1
      - pypika==0.48.9
      - pyproject-hooks==1.1.0
      - pyright==1.1.376
      - pysbd==0.3.4
      - pysocks==1.7.1
      - pytest==8.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytube==15.0.0
      - pytz==2024.1
      - pyyaml==6.0.2
      - qdrant-client==1.11.0
      - ratelimiter==1.2.0.post0
      - regex==2023.12.25
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retry==0.9.2
      - rich==13.7.1
      - rsa==4.9
      - s3transfer==0.10.2
      - safetensors==0.4.4
      - schema==0.7.7
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - selenium==4.23.1
      - semver==3.0.2
      - sentence-transformers==3.0.1
      - shapely==2.0.5
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==2.0.32
      - starlette==0.38.2
      - sympy==1.13.2
      - tabulate==0.9.0
      - tenacity==8.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - torch==2.4.0
      - tqdm==4.66.5
      - transformers==4.44.0
      - trio==0.26.2
      - trio-websocket==0.11.1
      - typer==0.12.3
      - types-requests==2.32.0.20240712
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - uvicorn==0.30.6
      - uvloop==0.20.0
      - watchfiles==0.23.0
      - websocket-client==1.8.0
      - websockets==12.0
      - wrapt==1.16.0
      - wsproto==1.2.0
      - yarl==1.9.4
      - zipp==3.20.0
prefix: /opt/anaconda3/envs/jejom-llama
